import React from 'react'
import ScrollIndicator from '../components/ScrollIndicator'

const ScrollIndicatorDemo = () => {
  return (
    <>
      <ScrollIndicator />
      <h1 className="m-8 text-center">Scroll Indicator</h1>
      <div className='text-xl'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid id magnam accusamus ipsa earum perferendis nobis nulla repudiandae explicabo, velit vel debitis. Ea ipsam amet temporibus porro. Exercitationem rerum voluptatem officia officiis provident harum iure dolor, quas esse cupiditate distinctio totam aspernatur facilis aut nesciunt commodi assumenda cumque iusto accusamus ratione mollitia autem incidunt. Nostrum, odit beatae pariatur laborum itaque minima qui, perferendis temporibus libero exercitationem dicta nisi fugit aut provident tenetur laboriosam accusantium nemo? Eos animi illo alias eius reiciendis. Deserunt, nisi voluptates sed quo, illum veritatis, eligendi doloremque temporibus officia distinctio vero! Doloremque, voluptate non? Cum fugit sequi et labore, culpa incidunt eaque deleniti ipsa, porro nihil recusandae nobis itaque dolores facere obcaecati! Ea, aperiam error maxime repellendus eveniet corporis sunt totam possimus saepe sint maiores iste quae quasi magnam assumenda modi eum expedita! Sed repellat distinctio iusto totam voluptatum voluptas magnam aliquid, dolorum unde fugiat id, veritatis recusandae beatae reprehenderit esse? Nobis, corrupti perspiciatis inventore fuga quam totam sint dicta rerum autem iste vero, cumque nam hic earum? Tempora nostrum tenetur numquam sit perferendis nisi vero voluptatibus quae facere corporis porro, ipsum, minima, nesciunt magnam expedita. Animi numquam quidem, tempore dolor atque omnis autem cupiditate deserunt. Quidem?</div>
      <div className='text-xl'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid id magnam accusamus ipsa earum perferendis nobis nulla repudiandae explicabo, velit vel debitis. Ea ipsam amet temporibus porro. Exercitationem rerum voluptatem officia officiis provident harum iure dolor, quas esse cupiditate distinctio totam aspernatur facilis aut nesciunt commodi assumenda cumque iusto accusamus ratione mollitia autem incidunt. Nostrum, odit beatae pariatur laborum itaque minima qui, perferendis temporibus libero exercitationem dicta nisi fugit aut provident tenetur laboriosam accusantium nemo? Eos animi illo alias eius reiciendis. Deserunt, nisi voluptates sed quo, illum veritatis, eligendi doloremque temporibus officia distinctio vero! Doloremque, voluptate non? Cum fugit sequi et labore, culpa incidunt eaque deleniti ipsa, porro nihil recusandae nobis itaque dolores facere obcaecati! Ea, aperiam error maxime repellendus eveniet corporis sunt totam possimus saepe sint maiores iste quae quasi magnam assumenda modi eum expedita! Sed repellat distinctio iusto totam voluptatum voluptas magnam aliquid, dolorum unde fugiat id, veritatis recusandae beatae reprehenderit esse? Nobis, corrupti perspiciatis inventore fuga quam totam sint dicta rerum autem iste vero, cumque nam hic earum? Tempora nostrum tenetur numquam sit perferendis nisi vero voluptatibus quae facere corporis porro, ipsum, minima, nesciunt magnam expedita. Animi numquam quidem, tempore dolor atque omnis autem cupiditate deserunt. Quidem?</div>
      <div className='text-xl'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid id magnam accusamus ipsa earum perferendis nobis nulla repudiandae explicabo, velit vel debitis. Ea ipsam amet temporibus porro. Exercitationem rerum voluptatem officia officiis provident harum iure dolor, quas esse cupiditate distinctio totam aspernatur facilis aut nesciunt commodi assumenda cumque iusto accusamus ratione mollitia autem incidunt. Nostrum, odit beatae pariatur laborum itaque minima qui, perferendis temporibus libero exercitationem dicta nisi fugit aut provident tenetur laboriosam accusantium nemo? Eos animi illo alias eius reiciendis. Deserunt, nisi voluptates sed quo, illum veritatis, eligendi doloremque temporibus officia distinctio vero! Doloremque, voluptate non? Cum fugit sequi et labore, culpa incidunt eaque deleniti ipsa, porro nihil recusandae nobis itaque dolores facere obcaecati! Ea, aperiam error maxime repellendus eveniet corporis sunt totam possimus saepe sint maiores iste quae quasi magnam assumenda modi eum expedita! Sed repellat distinctio iusto totam voluptatum voluptas magnam aliquid, dolorum unde fugiat id, veritatis recusandae beatae reprehenderit esse? Nobis, corrupti perspiciatis inventore fuga quam totam sint dicta rerum autem iste vero, cumque nam hic earum? Tempora nostrum tenetur numquam sit perferendis nisi vero voluptatibus quae facere corporis porro, ipsum, minima, nesciunt magnam expedita. Animi numquam quidem, tempore dolor atque omnis autem cupiditate deserunt. Quidem?</div>
      <div className='text-xl'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid id magnam accusamus ipsa earum perferendis nobis nulla repudiandae explicabo, velit vel debitis. Ea ipsam amet temporibus porro. Exercitationem rerum voluptatem officia officiis provident harum iure dolor, quas esse cupiditate distinctio totam aspernatur facilis aut nesciunt commodi assumenda cumque iusto accusamus ratione mollitia autem incidunt. Nostrum, odit beatae pariatur laborum itaque minima qui, perferendis temporibus libero exercitationem dicta nisi fugit aut provident tenetur laboriosam accusantium nemo? Eos animi illo alias eius reiciendis. Deserunt, nisi voluptates sed quo, illum veritatis, eligendi doloremque temporibus officia distinctio vero! Doloremque, voluptate non? Cum fugit sequi et labore, culpa incidunt eaque deleniti ipsa, porro nihil recusandae nobis itaque dolores facere obcaecati! Ea, aperiam error maxime repellendus eveniet corporis sunt totam possimus saepe sint maiores iste quae quasi magnam assumenda modi eum expedita! Sed repellat distinctio iusto totam voluptatum voluptas magnam aliquid, dolorum unde fugiat id, veritatis recusandae beatae reprehenderit esse? Nobis, corrupti perspiciatis inventore fuga quam totam sint dicta rerum autem iste vero, cumque nam hic earum? Tempora nostrum tenetur numquam sit perferendis nisi vero voluptatibus quae facere corporis porro, ipsum, minima, nesciunt magnam expedita. Animi numquam quidem, tempore dolor atque omnis autem cupiditate deserunt. Quidem?</div>
      <div className='text-xl'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid id magnam accusamus ipsa earum perferendis nobis nulla repudiandae explicabo, velit vel debitis. Ea ipsam amet temporibus porro. Exercitationem rerum voluptatem officia officiis provident harum iure dolor, quas esse cupiditate distinctio totam aspernatur facilis aut nesciunt commodi assumenda cumque iusto accusamus ratione mollitia autem incidunt. Nostrum, odit beatae pariatur laborum itaque minima qui, perferendis temporibus libero exercitationem dicta nisi fugit aut provident tenetur laboriosam accusantium nemo? Eos animi illo alias eius reiciendis. Deserunt, nisi voluptates sed quo, illum veritatis, eligendi doloremque temporibus officia distinctio vero! Doloremque, voluptate non? Cum fugit sequi et labore, culpa incidunt eaque deleniti ipsa, porro nihil recusandae nobis itaque dolores facere obcaecati! Ea, aperiam error maxime repellendus eveniet corporis sunt totam possimus saepe sint maiores iste quae quasi magnam assumenda modi eum expedita! Sed repellat distinctio iusto totam voluptatum voluptas magnam aliquid, dolorum unde fugiat id, veritatis recusandae beatae reprehenderit esse? Nobis, corrupti perspiciatis inventore fuga quam totam sint dicta rerum autem iste vero, cumque nam hic earum? Tempora nostrum tenetur numquam sit perferendis nisi vero voluptatibus quae facere corporis porro, ipsum, minima, nesciunt magnam expedita. Animi numquam quidem, tempore dolor atque omnis autem cupiditate deserunt. Quidem?</div>
    </>
  )
}

export default ScrollIndicatorDemo